sudo: required
language: node_js
node_js:
  - 14

cache:
  directories:
    - node_modules

before_script:
  - npm test

script:
  - npm run build

before_deploy:
  - VERSION=''
  - DEPLOY_DIRECTORY="public/"
  - 'if [ -n "$TRAVIS_TAG" ]; then
      VERSION=$TRAVIS_TAG;
      DEPLOY_DIRECTORY+="/$VERSION";
    fi'

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: $S3_BUCKET
    skip_cleanup: true
    local_dir: dist
    upload-dir: $DEPLOY_DIRECTORY
    on:
      tags: true

  - provider: npm
    email: "developers@teamwork.com"
    api_key: $NPM_TOKEN
    skip_cleanup: true
    tag: latest
    on:
      tags: true
      repo: Teamwork/public-components

